name: Build and push to local registry
on: pull_request
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - uses: buildpacks/github-actions/setup-pack@v5.5.4
      - uses: buildpacks/github-actions/setup-tools@v5.5.4
      - id: local-registry-push
        run: |
          ./pack-with-buildkit.sh
