name: Build and push to ghcr.io
on:
  push:
    branches:
      - "main"
env:
  PUBLISH_TO_GHCR_IO_IMAGE_URI: ghcr.io/jericop/inline-app:latest
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - uses: buildpacks/github-actions/setup-pack@v5.5.4
      - uses: buildpacks/github-actions/setup-tools@v5.5.4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - id: ghcr-push
        run: |
          ./pack-with-buildkit.sh
          
